import PDFDocument from 'pdfkit'
import type { TaxItem } from '@/lib/validations/sale'

export interface SalePdfData {
  saleNumber: string
  customerName?: string
  customerPhone?: string
  items: Array<{ name: string; quantity: number; price: number; subtotal: number }>
  subtotal: number
  discountPercent: number
  discount: number
  tax: number
  taxItems: TaxItem[]
  total: number
  paymentMethod: string
  notes?: string
  createdAt: string
}

export interface InvoicePdfData {
  invoiceNumber: string
  customerName: string
  customerEmail?: string
  customerPhone?: string
  customerAddress?: string
  items: Array<{ name: string; description?: string; quantity: number; price: number; total: number }>
  subtotal: number
  discountPercent: number
  discount: number
  tax: number
  taxItems: TaxItem[]
  total: number
  status: string
  dueDate: string
  notes?: string
  createdAt: string
}

export interface StoreInfo {
  name: string
  description?: string
  phone?: string
  email?: string
  address?: string
  taxNumber?: string
  footer?: string
}

const HEADER_COLOR = '#0f172a'
const HEADER_ACCENT = '#1e3a5f'
const TABLE_HEADER_BG = '#1e40af'
const ROW_EVEN = '#f8fafc'
const ROW_ODD = '#ffffff'
const BORDER_COLOR = '#e2e8f0'
const TEXT_PRIMARY = '#1e293b'
const TEXT_MUTED = '#64748b'
const SUCCESS_GREEN = '#059669'
const DISCOUNT_RED = '#dc2626'

function formatMoney(value: number): string {
  return `GHS ${value.toFixed(2)}`
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function drawTableRow(
  doc: PDFKit.PDFDocument,
  y: number,
  cols: string[],
  widths: number[],
  alignments: ('left' | 'right')[],
  isHeader = false,
  rowIndex?: number
) {
  let x = 50
  if (!isHeader && rowIndex !== undefined) {
    const rowColor = rowIndex % 2 === 0 ? ROW_EVEN : ROW_ODD
    doc.rect(x, y - 3, widths.reduce((a, b) => a + b, 0), 18).fill(rowColor)
    doc.fillColor(TEXT_PRIMARY)
  }

  if (isHeader) {
    doc.rect(x, y - 3, widths.reduce((a, b) => a + b, 0), 20).fill(TABLE_HEADER_BG)
    doc.fillColor('#ffffff')
  }

  cols.forEach((text, i) => {
    doc.fontSize(isHeader ? 8 : 8)
    doc.font(isHeader ? 'Helvetica-Bold' : 'Helvetica')
    const padding = isHeader ? 6 : 4
    if (alignments[i] === 'right') {
      doc.text(text, x + widths[i] - padding, y, { width: widths[i] - 4, align: 'right' })
    } else {
      doc.text(text, x + padding, y, { width: widths[i] - 8 })
    }
    x += widths[i]
  })

  if (!isHeader) {
    doc.fillColor(TEXT_PRIMARY)
  }
}

function drawA4Header(doc: PDFKit.PDFDocument, store: StoreInfo) {
  const startY = 40
  doc.rect(0, 0, doc.page.width, 110).fill(HEADER_COLOR)
  doc.rect(0, 110, doc.page.width, 4).fill(HEADER_ACCENT)

  // Logo placeholder
  doc.roundedRect(45, startY, 32, 32, 4).fill(HEADER_ACCENT)
  doc.fillColor('#ffffff').fontSize(16).font('Helvetica-Bold')
  doc.text('🏪', 50, startY + 6)
  doc.fillColor('#ffffff')

  doc.fontSize(18).font('Helvetica-Bold')
  doc.text(store.name, 88, startY + 2, { width: doc.page.width - 280 })

  if (store.description) {
    doc.fontSize(8).font('Helvetica-Oblique')
    doc.text(store.description, 88, startY + 22, { width: doc.page.width - 280 })
  }

  let infoY = startY
  const rightX = doc.page.width - 50
  const rightWidth = 200

  doc.fontSize(7).font('Helvetica')
  if (store.address) {
    doc.text(store.address, rightX - rightWidth, infoY, { width: rightWidth, align: 'right' })
    infoY += 10
  }
  if (store.phone) {
    doc.text(`Tel: ${store.phone}`, rightX - rightWidth, infoY, { width: rightWidth, align: 'right' })
    infoY += 10
  }
  if (store.email) {
    doc.text(store.email, rightX - rightWidth, infoY, { width: rightWidth, align: 'right' })
    infoY += 10
  }
  if (store.taxNumber) {
    doc.text(`Tax ID: ${store.taxNumber}`, rightX - rightWidth, infoY, { width: rightWidth, align: 'right' })
    infoY += 10
  }

  doc.fillColor(TEXT_PRIMARY)
}

function drawA4Footer(doc: PDFKit.PDFDocument, store: StoreInfo) {
  const bottomY = doc.page.height - 36
  doc.rect(0, bottomY - 6, doc.page.width, 42).fill('#f8fafc')
  doc.moveTo(50, bottomY - 6).lineTo(doc.page.width - 50, bottomY - 6).stroke(BORDER_COLOR)

  doc.fillColor(TEXT_MUTED).fontSize(8).font('Helvetica')
  doc.text(
    store.footer || 'Thank you for your business!',
    50,
    bottomY + 4,
    { align: 'center', width: doc.page.width - 100 }
  )

  doc.fontSize(7)
  const range = doc.bufferedPageRange() as { start: number; count: number } | null
  const pageText = `Page ${range ? range.start : 1}`
  doc.text(
    `${store.name} \u2022 Generated by IndFlow`,
    50,
    bottomY + 22,
    { width: 200, align: 'left' }
  )
  doc.text(pageText, doc.page.width - 50 - 80, bottomY + 22, { width: 80, align: 'right' })

  doc.fillColor(TEXT_PRIMARY)
}

interface DrawTotalsOpts {
  subtotal: number
  discountPercent: number
  discount: number
  taxItems: TaxItem[]
  tax: number
  total: number
  startX: number
  doc: PDFKit.PDFDocument
  width?: number
  includeDiscountLabel?: boolean
}

function drawTotals(opts: DrawTotalsOpts) {
  const { doc, startX } = opts
  const boxWidth = opts.width ?? 215
  let y = doc.y + 4

  doc.rect(startX, y - 4, boxWidth, 4).fill(TABLE_HEADER_BG)
  y += 4

  doc.fontSize(9).font('Helvetica').fillColor(TEXT_PRIMARY)

  doc.text('Subtotal', startX + 8, y, { width: boxWidth - 16 })
  doc.text(formatMoney(opts.subtotal), startX + 8, y, { width: boxWidth - 16, align: 'right' })
  y += 14

  if (opts.discount > 0) {
    const label = opts.includeDiscountLabel && opts.discountPercent > 0
      ? `Discount (${opts.discountPercent}%)`
      : 'Discount'
    doc.fillColor(TEXT_PRIMARY).text(label, startX + 8, y, { width: boxWidth - 16 })
    doc.fillColor(DISCOUNT_RED).text(`-${formatMoney(opts.discount)}`, startX + 8, y, { width: boxWidth - 16, align: 'right' })
    doc.fillColor(TEXT_PRIMARY)
    y += 14
  }

  if (opts.taxItems.length > 0) {
    for (const t of opts.taxItems) {
      doc.text(`${t.name} (${t.rate}%)`, startX + 8, y, { width: boxWidth - 16 })
      doc.text(formatMoney(t.amount), startX + 8, y, { width: boxWidth - 16, align: 'right' })
      y += 14
    }
  } else if (opts.tax > 0) {
    doc.text('Tax', startX + 8, y, { width: boxWidth - 16 })
    doc.text(formatMoney(opts.tax), startX + 8, y, { width: boxWidth - 16, align: 'right' })
    y += 14
  }

  doc.moveTo(startX, y).lineTo(startX + boxWidth, y).stroke(BORDER_COLOR)
  y += 6

  doc.fontSize(12).font('Helvetica-Bold').fillColor(TEXT_PRIMARY)
  doc.text('TOTAL', startX + 8, y, { width: boxWidth - 16 })
  doc.text(formatMoney(opts.total), startX + 8, y, { width: boxWidth - 16, align: 'right' })
  y += 18

  return y
}

export function generateSaleReceiptPdf(sale: SalePdfData, store: StoreInfo): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    // A5 width (148mm) for a thermal-receipt look
    const doc = new PDFDocument({ size: [280, 700], margin: 10 })
    const chunks: Buffer[] = []

    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const pageWidth = 280
    const margin = 20
    const contentWidth = pageWidth - margin * 2

    // --- Header (thermal receipt style with gradient bar) ---
    doc.rect(0, 0, pageWidth, 64).fill(HEADER_COLOR)
    doc.rect(0, 64, pageWidth, 3).fill(HEADER_ACCENT)

    doc.fillColor('#ffffff').fontSize(13).font('Helvetica-Bold')
    doc.text(store.name, margin, 10, { align: 'center', width: contentWidth })

    if (store.description) {
      doc.fontSize(7).font('Helvetica-Oblique')
      doc.text(store.description, margin, 26, { align: 'center', width: contentWidth })
    }

    doc.fontSize(6).font('Helvetica')
    let infoY = store.description ? 40 : 28
    if (store.address) {
      doc.text(store.address, margin, infoY, { align: 'center', width: contentWidth })
      infoY += 7
    }
    if (store.phone) {
      doc.text(`Tel: ${store.phone}`, margin, infoY, { align: 'center', width: contentWidth })
      infoY += 7
    }
    if (store.taxNumber) {
      doc.text(`Tax ID: ${store.taxNumber}`, margin, infoY, { align: 'center', width: contentWidth })
    }

    doc.fillColor(TEXT_PRIMARY)

    let y = 76

    // --- Receipt title ---
    doc.fontSize(10).font('Helvetica-Bold').fillColor(HEADER_COLOR)
    doc.text('RECEIPT', margin, y, { align: 'center', width: contentWidth })
    y += 14

    doc.fontSize(7).font('Helvetica').fillColor(TEXT_MUTED)
    doc.text(`#${sale.saleNumber}  \u2022  ${sale.createdAt}`, margin, y, { align: 'center', width: contentWidth })
    y += 12

    if (sale.customerName) {
      doc.fillColor(TEXT_PRIMARY).fontSize(7).font('Helvetica')
      doc.text(`Customer: ${sale.customerName}`, margin, y, { width: contentWidth })
      y += 9
      if (sale.customerPhone) {
        doc.text(`Phone: ${sale.customerPhone}`, margin, y, { width: contentWidth })
        y += 9
      }
    }

    y += 4
    doc.moveTo(margin, y).lineTo(pageWidth - margin, y).stroke(BORDER_COLOR)
    y += 6

    // --- Items table ---
    const colWidths = [contentWidth * 0.4, contentWidth * 0.18, contentWidth * 0.21, contentWidth * 0.21]
    const tableTotalWidth = colWidths.reduce((a, b) => a + b, 0)

    doc.rect(margin, y - 2, tableTotalWidth, 16).fill(TABLE_HEADER_BG)
    doc.fillColor('#ffffff').fontSize(6).font('Helvetica-Bold')
    let hx = margin
    ;['Item', 'Qty', 'Price', 'Total'].forEach((text, i) => {
      const pad = 3
      if (i === 0) doc.text(text, hx + pad, y + 1, { width: colWidths[i] - 6 })
      else doc.text(text, hx + colWidths[i] - pad, y + 1, { width: colWidths[i] - 2, align: 'right' })
      hx += colWidths[i]
    })
    doc.fillColor(TEXT_PRIMARY)
    y += 16

    sale.items.forEach((item, idx) => {
      const rowColor = idx % 2 === 0 ? ROW_EVEN : ROW_ODD
      doc.rect(margin, y - 2, tableTotalWidth, 14).fill(rowColor)
      doc.fillColor(TEXT_PRIMARY).fontSize(6).font('Helvetica')
      const values = [
        item.name.substring(0, 24),
        String(item.quantity),
        formatMoney(item.price),
        formatMoney(item.subtotal),
      ]
      let rx = margin
      values.forEach((text, i) => {
        const pad = 3
        if (i === 0) doc.text(text, rx + pad, y, { width: colWidths[i] - 6 })
        else doc.text(text, rx + colWidths[i] - pad, y, { width: colWidths[i] - 2, align: 'right' })
        rx += colWidths[i]
      })
      y += 14
    })

    y += 4
    doc.moveTo(margin, y).lineTo(pageWidth - margin, y).stroke(BORDER_COLOR)
    y += 6

    // --- Totals (discount, each tax, grand total) ---
    doc.fontSize(7).font('Helvetica')
    doc.text('Subtotal:', margin, y, { width: contentWidth - 70, continued: true })
    doc.text(formatMoney(sale.subtotal), { align: 'right', width: 70 })
    y += 11

    if (sale.discount > 0) {
      const label = sale.discountPercent > 0 ? `Discount (${sale.discountPercent}%):` : 'Discount:'
      doc.fillColor(DISCOUNT_RED)
      doc.text(label, margin, y, { width: contentWidth - 70, continued: true })
      doc.text(`-${formatMoney(sale.discount)}`, { align: 'right', width: 70 })
      doc.fillColor(TEXT_PRIMARY)
      y += 11
    }

    if (sale.taxItems.length > 0) {
      for (const t of sale.taxItems) {
        doc.text(`${t.name} (${t.rate}%):`, margin, y, { width: contentWidth - 70, continued: true })
        doc.text(formatMoney(t.amount), { align: 'right', width: 70 })
        y += 11
      }
    } else if (sale.tax > 0) {
      doc.text('Tax:', margin, y, { width: contentWidth - 70, continued: true })
      doc.text(formatMoney(sale.tax), { align: 'right', width: 70 })
      y += 11
    }

    doc.moveTo(margin, y).lineTo(pageWidth - margin, y).stroke(BORDER_COLOR)
    y += 5

    doc.fontSize(10).font('Helvetica-Bold')
    doc.text('TOTAL:', margin, y, { width: contentWidth - 70, continued: true })
    doc.text(formatMoney(sale.total), { align: 'right', width: 70 })
    y += 14

    // --- Payment method + PAID stamp ---
    doc.fontSize(7).font('Helvetica').fillColor(TEXT_MUTED)
    doc.text(`Paid via ${sale.paymentMethod}`, margin, y, { align: 'center', width: contentWidth })
    y += 12

    const paidY = y
    doc.rect(pageWidth - margin - 60, paidY, 60, 16).fill(SUCCESS_GREEN)
    doc.fillColor('#ffffff').fontSize(7).font('Helvetica-Bold')
    doc.text('PAID', pageWidth - margin - 60, paidY + 4, { align: 'center', width: 60 })
    doc.fillColor(TEXT_PRIMARY)

    y += 18

    if (sale.notes) {
      doc.fillColor(TEXT_MUTED).fontSize(6).font('Helvetica-Oblique')
      doc.text(sale.notes, margin, y, { align: 'center', width: contentWidth })
      y += 10
    }

    y += 6
    doc.fillColor(TEXT_MUTED).fontSize(6).font('Helvetica')
    doc.text(store.footer || 'Thank you for your purchase!', margin, y, { align: 'center', width: contentWidth })

    doc.end()
  })
}

export function generateInvoicePdf(invoice: InvoicePdfData, store: StoreInfo): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 })
    const chunks: Buffer[] = []

    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    drawA4Header(doc, store)

    let y = 130

    // --- Title + invoice number + status badge ---
    doc.fontSize(24).font('Helvetica-Bold').fillColor(HEADER_COLOR)
    doc.text('INVOICE', 380, y, { align: 'right' })
    y += 18

    doc.fontSize(10).font('Helvetica').fillColor(TEXT_MUTED)
    doc.text(`#${invoice.invoiceNumber}`, 380, y, { align: 'right' })
    y += 22

    const statusColors: Record<string, string> = {
      paid: SUCCESS_GREEN,
      sent: '#2563eb',
      draft: '#6b7280',
      overdue: '#dc2626',
      cancelled: '#6b7280',
    }
    const statusColor = statusColors[invoice.status] || '#6b7280'
    doc.roundedRect(425, y - 2, 80, 20, 5).fill(statusColor)
    doc.fillColor('#ffffff').fontSize(9).font('Helvetica-Bold')
    doc.text(
      invoice.status.charAt(0).toUpperCase() + invoice.status.slice(1),
      425,
      y + 2,
      { align: 'center', width: 80 }
    )
    doc.fillColor(TEXT_PRIMARY)
    y += 28

    // --- Bill To + Dates side-by-side ---
    doc.fontSize(10).font('Helvetica-Bold').fillColor(TEXT_PRIMARY)
    doc.text('Bill To:', 50, y)
    y += 14
    doc.fontSize(10).font('Helvetica').fillColor(TEXT_PRIMARY)
    doc.text(invoice.customerName, 50, y)
    y += 12
    if (invoice.customerEmail) { doc.text(invoice.customerEmail, 50, y); y += 11 }
    if (invoice.customerPhone) { doc.text(invoice.customerPhone, 50, y); y += 11 }
    if (invoice.customerAddress) { doc.text(invoice.customerAddress, 50, y, { width: 220 }); y += 11 }
    y += 4

    const rightStartX = 350
    let detailY = 130
    doc.fontSize(10).font('Helvetica').fillColor(TEXT_MUTED)
    doc.text('Invoice Date:', rightStartX, detailY)
    doc.fillColor(TEXT_PRIMARY).font('Helvetica-Bold')
    doc.text(invoice.createdAt, rightStartX + 100, detailY, { width: 145 })
    detailY += 14
    doc.fillColor(TEXT_MUTED).font('Helvetica')
    doc.text('Due Date:', rightStartX, detailY)
    doc.fillColor(TEXT_PRIMARY).font('Helvetica-Bold')
    doc.text(invoice.dueDate, rightStartX + 100, detailY, { width: 145 })
    detailY += 14
    if (store.taxNumber) {
      doc.fillColor(TEXT_MUTED).font('Helvetica')
      doc.text('Our Tax ID:', rightStartX, detailY)
      doc.fillColor(TEXT_PRIMARY).font('Helvetica-Bold')
      doc.text(store.taxNumber, rightStartX + 100, detailY, { width: 145 })
    }

    if (detailY > y) y = detailY
    y += 14

    // --- Items table ---
    doc.moveTo(50, y).lineTo(545, y).stroke(BORDER_COLOR)
    y += 8

    const colWidths = [200, 70, 110, 115]
    const tableTotalWidth = colWidths.reduce((a, b) => a + b, 0)

    doc.rect(50, y - 3, tableTotalWidth, 22).fill(TABLE_HEADER_BG)
    doc.fillColor('#ffffff').fontSize(9).font('Helvetica-Bold')
    let hx = 50
    ;['Description', 'Quantity', 'Unit Price', 'Total'].forEach((text, i) => {
      const pad = 8
      if (i === 0) doc.text(text, hx + pad, y + 2, { width: colWidths[i] - 8 })
      else doc.text(text, hx + colWidths[i] - pad, y + 2, { width: colWidths[i] - 4, align: 'right' })
      hx += colWidths[i]
    })
    doc.fillColor(TEXT_PRIMARY)
    y += 22

    invoice.items.forEach((item, idx) => {
      const rowHeight = item.description ? 26 : 18
      const rowColor = idx % 2 === 0 ? ROW_EVEN : ROW_ODD
      doc.rect(50, y - 3, tableTotalWidth, rowHeight).fill(rowColor)
      doc.fillColor(TEXT_PRIMARY).fontSize(9).font('Helvetica')
      let rx = 50
      const values = [
        item.description ? `${item.name}\n${item.description}` : item.name,
        String(item.quantity),
        formatMoney(item.price),
        formatMoney(item.total),
      ]
      values.forEach((text, i) => {
        const pad = 8
        if (i === 0) doc.text(text, rx + pad, y + 2, { width: colWidths[i] - 8 })
        else doc.text(text, rx + colWidths[i] - pad, y + 2, { width: colWidths[i] - 4, align: 'right' })
        rx += colWidths[i]
      })
      y += rowHeight
    })

    y += 10

    // --- Totals box on the right ---
    drawTotals({
      doc,
      startX: 330,
      width: 215,
      subtotal: invoice.subtotal,
      discountPercent: invoice.discountPercent,
      discount: invoice.discount,
      taxItems: invoice.taxItems,
      tax: invoice.tax,
      total: invoice.total,
      includeDiscountLabel: true,
    })

    if (invoice.notes) {
      doc.moveDown(2)
      doc.fontSize(10).font('Helvetica-Bold').fillColor(TEXT_PRIMARY)
      doc.text('Notes / Terms:')
      doc.moveDown(0.4)
      doc.font('Helvetica').fillColor(TEXT_MUTED)
      doc.text(invoice.notes, { width: 280 })
    }

    drawA4Footer(doc, store)

    doc.end()
  })
}
